/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pHash */

#ifndef _Included_pHash
#define _Included_pHash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pHash
 * Method:    calculateHash
 * Signature: (Ljava/lang/String;I)Ljava/util/BitSet;
 */
JNIEXPORT jobject JNICALL Java_pHash_calculateHash
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
