/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __org_phash_MVPTree__
#define __org_phash_MVPTree__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jboolean JNICALL Java_org_phash_MVPTree_create (JNIEnv *env, jobject, jobjectArray);
JNIEXPORT jobjectArray JNICALL Java_org_phash_MVPTree_query (JNIEnv *env, jobject, jobject, jfloat, jfloat, jint);
JNIEXPORT jboolean JNICALL Java_org_phash_MVPTree_add (JNIEnv *env, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif

#endif /* __org_phash_MVPTree__ */
