/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pHash */

#ifndef _Included_pHash
#define _Included_pHash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pHash
 * Method:    videoHash
 * Signature: (Ljava/lang/String;)LpHash/VideoHash;
 */
JNIEXPORT jobject JNICALL Java_pHash_videoHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pHash
 * Method:    audioHash
 * Signature: (Ljava/lang/String;)LpHash/AudioHash;
 */
JNIEXPORT jobject JNICALL Java_pHash_audioHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pHash
 * Method:    imageHash
 * Signature: (Ljava/lang/String;)LpHash/ImageHash;
 */
JNIEXPORT jobject JNICALL Java_pHash_imageHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pHash
 * Method:    textHash
 * Signature: (Ljava/lang/String;)LpHash/TextHash;
 */
JNIEXPORT jobject JNICALL Java_pHash_textHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pHash
 * Method:    imageDistance
 * Signature: (LpHash/ImageHash;LpHash/ImageHash;)I
 */
JNIEXPORT jint JNICALL Java_pHash_imageDistance
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     pHash
 * Method:    audioDistance
 * Signature: (LpHash/AudioHash;LpHash/AudioHash;)D
 */
JNIEXPORT jdouble JNICALL Java_pHash_audioDistance
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     pHash
 * Method:    videoDistance
 * Signature: (LpHash/VideoHash;LpHash/VideoHash;)I
 */
JNIEXPORT jint JNICALL Java_pHash_videoDistance
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     pHash
 * Method:    textDistance
 * Signature: (LpHash/TextHash;LpHash/TextHash;)I
 */
JNIEXPORT jint JNICALL Java_pHash_textDistance
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     pHash
 * Method:    pHashInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pHash_pHashInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
