/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pHash_MVPTree */

#ifndef _Included_pHash_MVPTree
#define _Included_pHash_MVPTree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pHash_MVPTree
 * Method:    create
 * Signature: (Ljava/lang/String;[LpHash/Hash;)Z
 */
JNIEXPORT jboolean JNICALL Java_pHash_00024MVPTree_create
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     pHash_MVPTree
 * Method:    query
 * Signature: (Ljava/lang/String;FI)[LpHash/Hash;
 */
JNIEXPORT jobjectArray JNICALL Java_pHash_00024MVPTree_query
  (JNIEnv *, jobject, jstring, jfloat, jint);

/*
 * Class:     pHash_MVPTree
 * Method:    add
 * Signature: ([LpHash/Hash;)Z
 */
JNIEXPORT jboolean JNICALL Java_pHash_00024MVPTree_add
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
