/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pHash */

#ifndef _Included_pHash
#define _Included_pHash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pHash
 * Method:    videoHash
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_pHash_videoHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pHash
 * Method:    audioHash
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_pHash_audioHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pHash
 * Method:    imageHash
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_pHash_imageHash
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pHash
 * Method:    imageDistance
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_pHash_imageDistance
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     pHash
 * Method:    audioDistance
 * Signature: ([I[I)D
 */
JNIEXPORT jdouble JNICALL Java_pHash_audioDistance
  (JNIEnv *, jclass, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
