/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MVPTree */

#ifndef _Included_MVPTree
#define _Included_MVPTree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MVPTree
 * Method:    create
 * Signature: ([LHash;)Z
 */
JNIEXPORT jboolean JNICALL Java_MVPTree_create
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     MVPTree
 * Method:    query
 * Signature: (LHash;FI)[LHash;
 */
JNIEXPORT jobjectArray JNICALL Java_MVPTree_query
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jint);

/*
 * Class:     MVPTree
 * Method:    add
 * Signature: ([LHash;)Z
 */
JNIEXPORT jboolean JNICALL Java_MVPTree_add
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
